### ISSUE TITLE
Complete Initial Project EDA

### ISSUE THREAD

**Issue by sam-mata** [sam-mata/antarctic-genetic-modelling#33]
### Details
Please give details about the preferred changes.

### To-Do:
- [x] Examine and plot inter-feature correlations for possible dimensionality reductions _(Bivariate Analysis)_ 
- [x] Examine and plot feature-output correlations
- [x] Visualise feature changes over time _(Temporal Analysis)_
- [x] Visualise feature distribution _(Univariate Analysis)_
- [x] Examine and plot regional variations in features _(Spatial Analysis)_
- [x] Examine feature creations, possibly to account for long term lag _(i.e. derivatives & integrals)_
